# Spectral configuration for Insomnia - disables specific linting errors
extends: spectral:oas
rules:
  # Disable the EXACT errors you're seeing
  info-contact: off
  path-keys-no-trailing-slash: off
  operation-tags: off
  operation-tag-defined: off
  
  # Disable all other common rules
  operation-operationId: off
  operation-description: off
  operation-parameters: off
  operation-request-body: off
  operation-response: off
  operation-success-response: off
  operation-operationId-unique: off
  operation-response-examples: off
  operation-request-body-examples: off
  tag-description: off
  openapi-tags: off
  openapi-tags-uniqueness: off
  path-params: off
  path-declaration-must-exist: off
  oas3-valid-schema-example: off
  oas3-valid-media-example: off
  oas3-valid-oas-content-example: off
  oas3-schema: off
  no-$ref-siblings: off
  no-unresolved-refs: off
  oas3-api-servers: off
  oas3-server-trailing-slash: off
  operation-security-defined: off
  oas3-operation-security-defined: off
  oas3-security-defined: off
  oas3-parameter-description: off
  oas3-parameter-examples: off
  oas3-unused-component: off
  info-description: off
  info-license: off
