# Generated by Django 5.2.8 on 2025-11-18 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0006_category_poll_category_tag_poll_tags_and_more'),
        ('votes', '0003_rename_votes_vote_poll_id_voter_t_idx_votes_vote_poll_id_6f9005_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('poll_results_available', 'Poll Results Available'), ('new_poll_from_followed', 'New Poll from Followed Creator'), ('poll_about_to_expire', 'Poll About to Expire'), ('vote_flagged', 'Your Vote Was Flagged')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(blank=True, help_text='Related poll (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='polls.poll')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(blank=True, help_text='Related vote (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='votes.vote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('push', 'Push Notification')], help_text='Delivery channel', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], db_index=True, default='pending', help_text='Delivery status', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('external_id', models.CharField(blank=True, help_text='External ID from delivery service (e.g., email message ID)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(help_text='Notification being delivered', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name_plural': 'Notification Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_results_available_email', models.BooleanField(default=True, help_text='Email for poll results')),
                ('poll_results_available_in_app', models.BooleanField(default=True, help_text='In-app for poll results')),
                ('poll_results_available_push', models.BooleanField(default=False, help_text='Push for poll results')),
                ('new_poll_from_followed_email', models.BooleanField(default=True, help_text='Email for new polls from followed creators')),
                ('new_poll_from_followed_in_app', models.BooleanField(default=True, help_text='In-app for new polls from followed creators')),
                ('new_poll_from_followed_push', models.BooleanField(default=False, help_text='Push for new polls from followed creators')),
                ('poll_about_to_expire_email', models.BooleanField(default=True, help_text='Email for poll expiration warnings')),
                ('poll_about_to_expire_in_app', models.BooleanField(default=True, help_text='In-app for poll expiration warnings')),
                ('poll_about_to_expire_push', models.BooleanField(default=False, help_text='Push for poll expiration warnings')),
                ('vote_flagged_email', models.BooleanField(default=True, help_text='Email for flagged votes')),
                ('vote_flagged_in_app', models.BooleanField(default=True, help_text='In-app for flagged votes')),
                ('vote_flagged_push', models.BooleanField(default=False, help_text='Push for flagged votes')),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable all email notifications')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Enable all in-app notifications')),
                ('push_enabled', models.BooleanField(default=False, help_text='Enable all push notifications')),
                ('unsubscribed', models.BooleanField(default=False, help_text='User has unsubscribed from all notifications')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When user unsubscribed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['poll', 'created_at'], name='notificatio_poll_id_02e560_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_1e9b53_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_edd073_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationdelivery',
            unique_together={('notification', 'channel')},
        ),
    ]
