# Generated by Django 5.2.8 on 2025-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_update_vote_and_add_voteattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_poll_id_6f9005_idx',
            old_name='votes_vote_poll_id_voter_t_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_idempot_31932d_idx',
            old_name='votes_vote_idempotency_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_ip_addr_2a2a89_idx',
            old_name='votes_vote_ip_addr_created_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_user_id_bc6d81_idx',
            old_name='votes_vote_user_id_poll_id_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_poll_id_62f9ba_idx',
            old_name='votes_vote_poll_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_fingerp_f65f2c_idx',
            old_name='votes_vote_fingerprint_created_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='votes_vote_is_vali_d13103_idx',
            old_name='votes_vote_is_valid_poll_idx',
        ),
        migrations.RenameIndex(
            model_name='voteattempt',
            new_name='votes_votea_poll_id_7aa7b0_idx',
            old_name='votes_voteattempt_poll_voter_idx',
        ),
        migrations.RenameIndex(
            model_name='voteattempt',
            new_name='votes_votea_idempot_b414c7_idx',
            old_name='votes_voteattempt_idempotency_idx',
        ),
        migrations.RenameIndex(
            model_name='voteattempt',
            new_name='votes_votea_ip_addr_b2c265_idx',
            old_name='votes_voteattempt_ip_created_idx',
        ),
        migrations.RenameIndex(
            model_name='voteattempt',
            new_name='votes_votea_success_9b5eec_idx',
            old_name='votes_voteattempt_success_created_idx',
        ),
        migrations.RenameIndex(
            model_name='voteattempt',
            new_name='votes_votea_poll_id_c39f95_idx',
            old_name='votes_voteattempt_poll_created_idx',
        ),
        migrations.AlterField(
            model_name='vote',
            name='idempotency_key',
            field=models.CharField(db_index=True, help_text='Unique key for idempotent operations', max_length=64, unique=True),
        ),
    ]
